### ISSUE TITLE
Citeproc messes with fonts in Typst

### ISSUE THREAD

**Issue by the-solipsist** [quarto-dev/quarto-cli#13773]
### I have:

- [x] searched the issue tracker for similar issues
- [x] installed the latest version of [Quarto CLI](https://github.com/quarto-dev/quarto-cli/releases/latest)
- [x] formatted my issue following the [Bug Reports guide](https://quarto.org/bug-reports.html)

### Bug description

Fonts in an extension / brand.yml do not work properly with Typst if `citeproc` is used with a bibliography. They work fine if `citeproc` is not used.

I'm not sure if this is a Pandoc problem or a Quarto problem.  I searched on both repos, but couldn't find a relevant bug report.

I'm also not sure if this is an issue just with Typst or with other output formats as well.

### Steps to reproduce

Here's a MWE:
https://github.com/the-solipsist/quarto-font-test

in `_quarto.yml`, set  `citeproc: false` [EDIT: and comment out the bibliography]
https://github.com/the-solipsist/quarto-font-test/blob/main/_quarto.yml#L9

Run `quarto render`.

Then change it to `citeproc: true` [EDIT: and keep the bibliography line]

Run `quarto render`.

### Actual behavior

```
[typst]: Compiling d4dasia_country-report_sl_blank.typ to d4dasia_country-report_sl_blank.pdf...warning: unknown font family: montserrat
    ┌─ country/sl/d4dasia_country-report_sl_blank.typ:637:30
    │
637 │ #show heading: set text(font: ("Montserrat",), weight: "bold", fill: rgb("#a51212"), )
    │                               ^^^^^^^^^^^^^^^

warning: unknown font family: sorts mill goudy
    ┌─ country/sl/d4dasia_country-report_sl_blank.typ:283:10
    │
283 │     font: font,
    │           ^^^^

warning: unknown font family: montserrat
    ┌─ country/sl/d4dasia_country-report_sl_blank.typ:429:23
    │
429 │         set text(font: heading-family, weight: heading-weight, style: heading-style, fill: heading-color)
    │                        ^^^^^^^^^^^^^^
```

### Expected behavior

It should compile fine with the fonts having been downloaded:
```
[typst]: Compiling d4dasia_country-report_sl_blank.typ to d4dasia_country-report_sl_blank.pdf...DONE
```

And the fonts should be in `.quarto`:
```
❯ ls -R .quarto/typst-font-cache/
.quarto/typst-font-cache/:
fonts.gstatic.com/

.quarto/typst-font-cache/fonts.gstatic.com:
s/

.quarto/typst-font-cache/fonts.gstatic.com/s:
montserrat/  sarabun/  sortsmillgoudy/

.quarto/typst-font-cache/fonts.gstatic.com/s/montserrat:
v31/

.quarto/typst-font-cache/fonts.gstatic.com/s/montserrat/v31:
JTUHjIg1_i6t8kCHKm4532VJOt5-QNFgpCtr6Hw5aX8.ttf

.quarto/typst-font-cache/fonts.gstatic.com/s/sarabun:
v17/

.quarto/typst-font-cache/fonts.gstatic.com/s/sarabun/v17:
DtVjJx26TKEr37c9aBVJmg.ttf

.quarto/typst-font-cache/fonts.gstatic.com/s/sortsmillgoudy:
v16/

.quarto/typst-font-cache/fonts.gstatic.com/s/sortsmillgoudy/v16:
Qw3GZR9MED_6PSuS_50nEaVrfzgEbHoEig.ttf
```

### Your environment

- OS: EndeavourOS (Arch-based rolling release)

### Quarto check output

```
sol@spica /tmp/test (main) 
❯ quarto check
Quarto 1.9.12
[✓] Checking environment information...
      Quarto cache location: /home/sol/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.6.3: OK
      Dart Sass version 1.87.0: OK
      NOTE: Deno version 2.4.5 does not strictly match 2.3.1 and strict checking is enabled. Please use 2.3.1.
      Typst version 0.13.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.9.12
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking Chrome Headless....................OK
      Chrome:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.13.7
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cderv** [comment]
Thanks for the report. I am trying to reproduce but with `citeproc: false` I get
````
[typst]: Compiling d4dasia_country-report_sl_blank.typ to d4dasia_country-report_sl_blank.pdf...error: unknown bibliography format (must be .yml/.yaml or .bib)
    ┌─ \\?\C:\Users\chris\AppData\Local\Temp\quarto\quarto-font-test\country\sl\d4dasia_country-report_sl_blank.typ:768:14
    │
768 │ #bibliography(("../../shared/d4dasia-bib.json"))
    │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

````

Is this is expected ? 

Probably because using `json` format rely on citeproc being used ? 

Just to be sure. 

Also it would be helpful to reduce a little more the example. This is using extensions, brand, custom partials template. So it could come from different places, and reducing would help understand what triggers this. As of now, it could either be a bug, or a malformed partial, or misconfigured configuration. 

Thanks !

**Comment by cderv** [comment]
And by the way, this is possible related to 
- https://github.com/quarto-dev/quarto-cli/issues/13745

which is an issue I opened following your last report on same extension @the-solipsist 

So until this other issue is solved, you may encounter problem with fonts as they won't be found. 

So possibly this issue is a duplicate as `citeproc: false` fails before typst can be processed.

**Comment by the-solipsist** [comment]
Sorry, you need to comment out the bibliography when setting `citeproc: false`.  I forgot to add that.  (Typst expects the Hayagriva format, not the CSL JSON  /CSL YAML format.)

I think this might be related to #13745, but in the reverse direction: I think this might be the root cause, rather than that.

If I set `citeproc: false`, then relative font paths work in the format extension!

So it is something in the interaction of citeproc with fonts that's causing the multiple issues I've had all week.  And that's also the reason they've not shown up for other people.

**Comment by the-solipsist** [comment]
I've pushed a new commit to the repo, removing the Typst template partial. So the moving parts are:

1. Citeproc in _quarto.yml
2. Fonts in _brand.yml within an extension

If `citeproc: true`:
- For the fonts, it doesn't matter if they are set by (a) file path, or (b) Google Fonts, it doesn't work.
- If the font is present in the system, fonts works.
- It doesn't matter if fonts are set in `_quarto.yml` or `_brand.yml`, or within an extension or outside of the extension.

I hope that helps clarify.

**Comment by cderv** [comment]
Thanks, now after `git pull` of your change, and `quarto render` I get
````
[typst]: Compiling d4dasia_country-report_sl_blank.typ to d4dasia_country-report_sl_blank.pdf...warning: unknown font family: sorts mill goudy
    ┌─ \\?\C:\Users\chris\AppData\Local\Temp\quarto\quarto-font-test\country\sl\d4dasia_country-report_sl_blank.typ:205:17
    │
205 │            font: font,
    │                  ^^^^

DONE

Output created: country\sl\d4dasia_country-report_sl_blank.pdf
````

So some fonts still unknown, but it seems it renders. 

Activating `citeproc: true` indeed triggers another error, which is unexpected. 

I'm not sure if this is the root cause. My analysis and debug in #13745 still show some problem when resolving path of extension in nested documents. 

Anyhow, I'll have a look in this citreproc interaction

**Comment by cderv** [comment]
Though what is this change in your extension 
````
    - family: Sorts Mill Goudy
      source: file
      files:
        - path: /tmp/test/_extensions/lirneasia/assets/fonts/sortsmillgoudy/SortsMillGoudy-Regular.ttf
````

Are we supposed to have something in `/tmp/test` ? 

https://github.com/the-solipsist/quarto-font-test/commit/a77d7e1e6637d17ccc0ff7b8f956683d57d67b87 is not really helpful to reproduce on our side. 🤔 

Anyhow, I changed it which removed previous error shared just above .

**Comment by cderv** [comment]
Thanks to your report we indeed found a bad issue !! 

when `citeproc: true`, we need to opt-out typst's citation by doing `typst-citations` as format. 

and when this happens we are badly failing  to detect Typst format correctly so we do skip all the brand logic (meaning font are not handled) 
https://github.com/quarto-dev/quarto-cli/blob/87f18c876759c619b0573105cf6ada7fab0fb6b3/src/command/render/pandoc.ts#L1472-L1474

I'll work on a smaller reprex and the proper fix. 

Pandoc may have changed its way of handling citation in typst which may remove the need of the trick we used.

**Comment by the-solipsist** [comment]
Sorry, I've not been producing proper examples. I tried with an absolute path (for one font) and a relative path (for another font), just to make sure they were working. I accidentally committed the absolute path as well. I fixed that and pushed to the test repo once again.

But as you discovered (with a relative path) the font works as intended when `citeproc: false`, but fails when `citeproc: true`.

**Comment by cderv** [comment]
For now I have opened
- https://github.com/quarto-dev/quarto-cli/issues/13775

to solve the issue related to brand logic not applying. 

I'll look after if this solves this one or not, as maybe there is more to it. We'll see

**Comment by the-solipsist** [comment]
Thanks. Since I need to use `citeproc`, for now my workaround is to ensure that the fonts are installed at the system level.

I'm glad we were able to figure out the bug.  I was going mad for a while being unable to get things working.  Since there's #13775, feel free to close this report.

**Comment by the-solipsist** [comment]
I tested with pre-release 1.9.13, which included https://github.com/quarto-dev/quarto-cli/pull/13777, and everything works as expected. Thanks! Closing this issue.

**Comment by cderv** [comment]
Thank for confirming ! So it seems it was the only error then.
