### ISSUE TITLE
Evaluating R code with `!expr` in `fig-subcap` doesn't work

### ISSUE THREAD

**Issue by svraka** [quarto-dev/quarto-cli#2047]
### Bug description

It is [documented](https://quarto.org/docs/computations/r.html#chunk-options) that `!expr` works with `fig-cap`, but it doesn't work with `fig-subcap`.

````md
```{r}
#| label: fig-charts
#| fig-cap: Charts
#| fig-subcap: !expr c("First", "Second")

plot(cars)
plot(pressure)
```
````

I get the following error when running `quarto render` on the file:

```
ERROR: Validation of YAML cell metadata failed.
In file subfig-eval-yaml.qmd
(line 4, columns 16--42) Key fig-subcap has value !expr c("First", "Second"), which must be 'true'
3: #| fig-cap: Charts
4: #| fig-subcap: !expr c("First", "Second")
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~

ERROR: Render failed due to invalid YAML.
```

### `quarto check` Output

```
[>] Checking Quarto installation......OK
      Version: 1.0.38
      Path: C:\scoop\apps\quarto\current\bin\
      CodePage: 1250

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: C:/msys64/mingw64/bin/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/scoop/apps/r-release/current
      LibPaths:
        - C:/scoop/apps/r-release/4.2.1/library
      rmarkdown: 2.15

[>] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```
[>] Inspecting tools

Tool         Status                    Installed     Latest  
chromium     Not installed             ---           869685  
tinytex      External Installation     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Can you upgrade to the latest prerelease version of quarto here? https://github.com/quarto-dev/quarto-cli/releases/tag/v1.1.109

You're likely seeing what's not a bug, but rather an issue in your YAML: !expr needs a string parameter, and so you need to escape those quotes. The latest version has better error messages in this case.

**Comment by svraka** [comment]
> Can you upgrade to the latest prerelease version of quarto here? https://github.com/quarto-dev/quarto-cli/releases/tag/v1.1.109

Error is the same with 1.1.109. 

> You're likely seeing what's not a bug, but rather an issue in your YAML: !expr needs a string parameter, and so you need to escape those quotes. The latest version has better error messages in this case.

I dont't understand your comment. The same code with `fig-cap` instead of `fig-subcap` works and doesn't need any escaping---as it is explained in the documentation I linked.

````md
```{r}
#| label: fig-charts
#| fig-cap: !expr c("First", "Second")

plot(cars)
plot(pressure)
```
````

**Comment by cscheid** [comment]
I apologize - I read the error message entirely wrong.

Unfortunately, this won't be easy for us to fix right now; The issue is that the validator sees a datatype of string, and can't in general know that the output you're generating is an array of strings. You can work around this issue by disabling yaml validation for the entire document, with

```
---
validate-yaml: false
---
```

But this means there won't be any validation of yaml across the entire quarto document.

**Comment by svraka** [comment]
`validate-yaml: false` works indeed.

Does this mean you have special code to handle `fig-cap?` Or how else can `fig-cap: !expr c("First", "Second")` be valid YAML, while `fig-subcap: !expr c("First", "Second")` is not?

**Comment by schwa021** [comment]
> `validate-yaml: false` works indeed.
> 
> Does this mean you have special code to handle `fig-cap?` Or how else can `fig-cap: !expr c("First", "Second")` be valid YAML, while `fig-subcap: !expr c("First", "Second")` is not?

FYI - I just tried this 1.3.306 and it worked fine without having to invalidate the YAML. Perhaps this has been fixed?

**Comment by egouldo** [comment]
> > `validate-yaml: false` works indeed.
> > Does this mean you have special code to handle `fig-cap?` Or how else can `fig-cap: !expr c("First", "Second")` be valid YAML, while `fig-subcap: !expr c("First", "Second")` is not?
> 
> FYI - I just tried this 1.3.306 and it worked fine without having to invalidate the YAML. Perhaps this has been fixed?

Just downloaded and installed 1.3.450 and it's not working for me.

**Comment by cderv** [comment]
So I believe this works ok now **using Quarto 1.4** which is pre-release. 

<table>
<tr>
 <td>

````markdown
---
title: "test"
format: html
---

```{r}
#| label: fig-charts
#| fig-cap: Charts
#| fig-subcap: !expr c("First", "Second")

plot(cars)
plot(pressure)
```
````

 <td>

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/2c2a1415-8b3d-4833-803d-257e581bf557)

</table>

You'll still get the warning in YAML linting for what is mentioned already in this thread. 

So you should not need R to create a list 
````markdown
```{r}
#| label: fig-charts
#| fig-cap: Charts
#| fig-subcap: 
#|   - First
#|   - Second

plot(cars)
plot(pressure)
```
````


New cross ref system allows you to express with Div figures and could be interesting to use inline code inside captions for example to avoid use of `!expr` when you need add a caption with text from evaluation


````markdown
---
title: "test"
format: html
---

See @fig-example-multiple-chunks, @fig-subfig-1 and @fig-subfig-2.

::: {#fig-example-multiple-chunks layout="[[ 25, 75 ]]"}

::: {#fig-subfig-1}
```{r}
#| echo: false
#| fig-width: 2
#| fig-height: 5
plot(cars)
```

This dataset has `r nrow(cars)` rows.

:::

```{r}
#| label: fig-subfig-2
#| fig-cap: "I don't care about the number of rows on this one."
#| echo: false
#| fig-width: 6
#| fig-height: 5
plot(pressure)
```

Charts

:::

````

**Comment by cderv** [comment]
Let's close this issue now that we have one report specific to `!expr`

- https://github.com/quarto-dev/quarto-cli/issues/12044
