### ISSUE TITLE
Can't render Quarto to PDF

### ISSUE THREAD

**Issue by lightbluetitan** [quarto-dev/quarto-cli#2245]
### Bug description

Hi Guys

Everytime I try to render a Quarto documento to PDF I got an error about LaTeX and xelatex, could you help me with that?
Working with Windows 10, R 4.2.1, RStudio 2022.07.1
![image](https://user-images.githubusercontent.com/13672461/187830528-e5f544ff-63d0-4d59-8952-a397be7efa4b.png)
This is my yaml header
`---
title: Bar Charts - R
date: today
description: El presente documento muestra como crear diagramas de barras (Bar Charts) en el lenguaje de programación R haciendo uso de la función barplot(), así como de los paquetes (packages) ggplot2 y lattice.
author: 
   name: Renzo Cácerers Rossi
   url: https://www.youtube.com/c/RenzoCaceresRossi
   affiliation: Rossi Corporation
   affiliation-url: https://hablamosr.blogspot.com/
title-block-banner: "#808080"
format: 
  pdf: 
    theme: journal
    toc: true
    css: "style_003.css"
    code-fold: true
    code-tools: true
bibliography: biblio_003.bib
csl: apa.csl
link-citations: yes
number-sections: true
lang: Es-es
prefer-html: true
---`

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
From the error above it appears that something in injecting HTML into the LaTeX document (the `link` tag pointing at vembedr.css in the error above). Perhaps you are attempting to embed HTML content in a PDF? If you can share a complete example qmd that would make it easier to diagnose.

**Comment by cderv** [comment]
@lightbluetitan can you share you quarto version by running `quarto check` in RStudio terminal ? 

It is possible you get an old Quarto version. A bug like that was reported some time ago (https://github.com/quarto-dev/quarto-cli/issues/1378) and should have been fixed in v1.0.20 and above. 

thank you

**Comment by lightbluetitan** [comment]
> @lightbluetitan can you share you quarto version by running `quarto check` in RStudio terminal ?
> 
> It is possible you get an old Quarto version. A bug like that was reported some time ago (#1378) and should have been fixed in v1.0.20 and above.
> 
> thank you

hi cderv

It seems I got an updated version of Quarto, but the problem remains
![image](https://user-images.githubusercontent.com/13672461/187980421-f0b5c79f-4e49-4c55-ab7e-62f3e980ef60.png)

**Comment by cderv** [comment]
Is it possible for you to install the latest quarto version to really check if the issue is here ? 
We've done a lot of work since 1.0.36: https://quarto.org/docs/get-started/ 

Thank you
