### ISSUE TITLE
rust launcher: crash on retrieving exit code from deno

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#2296]
@jph00 reports:

I just tried it with the latest quarto, and in a directory with just a single ipynb and a minimal _quarto.yml I got this error:

```
$ RUST_BACKTRACE=full quarto render
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
thread 'main' panicked at 'failed to get deno exit code', src/main.rs:101:37
stack backtrace:
   0:        0x100d6bb24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85521558a183f368
   1:        0x100d82b8b - core::fmt::write::h01631fae0d2b98bc
   2:        0x100d68d78 - std::io::Write::write_fmt::h675dde99a2999169
   3:        0x100d6d0ad - std::panicking::default_hook::{{closure}}::h5e5df492d229fd65
   4:        0x100d6ce04 - std::panicking::default_hook::h18647b59f1a84ee2
   5:        0x100d6d5e8 - std::panicking::rust_panic_with_hook::hd9ead35a68ccc55e
   6:        0x100d6d523 - std::panicking::begin_panic_handler::{{closure}}::h6fca91c5e1dc2f30
   7:        0x100d6bfa7 - std::sys_common::backtrace::__rust_end_short_backtrace::h4ff3025d9a0a0490
   8:        0x100d6d1fa - _rust_begin_unwind
   9:        0x100d89843 - core::panicking::panic_fmt::h3d9f795ee387ef8d
  10:        0x100d81d7b - core::panicking::panic_display::h57aa0e5ca0e6a595
  11:        0x100d81d2c - core::panicking::panic_str::h13f91ca11a013f3e
  12:        0x100d896d9 - core::option::expect_failed::hed5528a77aee7737
  13:        0x100d47709 - quarto::main::hcf1aaa9959ffbc6d
  14:        0x100d480b6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9f94d688d5885adb
  15:        0x100d4812c - std::rt::lang_start::{{closure}}::h58a78b66d00be7f2
  16:        0x100d6504e - std::rt::lang_start_internal::h3fd5cff071397f19
  17:        0x100d48019 - _main
```

Here's the `_quarto.yml`

```yaml
project:
  type: website

website:
  title: "testquarto"
  description: "Experimenting with quarto"
  sidebar:
    contents:
      - index.ipynb
```

**Comment by jjallaire** [comment]
@jph00 IIRC you are on an M1 Mac, correct? (there may be differences as in v1.2 we are now using the aarch64 version of Deno).

I just committed a fix which _should_ work around the crash: https://github.com/quarto-dev/quarto-cli/commit/6a5916830c24e6e3f93454f78b6c0dc717f8e42f. That is available as [pre-release 1.2.161 ](https://quarto.org/docs/download/prerelease.html)-- could you try again with this version?

@cscheid Are you able to reproduce this (w/ the previous pre-release binary) on your M1 Max? If so let's try to dig in to exactly what's going on under the hood.

**Comment by jph00** [comment]
@jjallaire I'm on an M2 Mac.

The fix you provided has changed the error I receive to this one:

```
$ RUST_BACKTRACE=full quarto render

assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
```

To check whether it was an ipynb issue, I replaced my notebook with an `index.qmd` file, and still get the same error. The `_quarto.yml` is as in the issue description above, and the qmd is:

```
---
title: hi
---

there
```

I also tried removing the contents of `~/Library/Caches/quarto/` but that didn't fix the problem.

**Comment by jjallaire** [comment]
That's dispiriting!  You actually reported this same crash when we originally updated to Deno 1.23 a while back. We reproduced the crash on the M1 Max but had actually (we thought) moved past it by running the aarch64 native version of Deno 1.25 (which had a new version of V8 that fixed some aarch64 issues). Anyway, I would expect to see that crash if somehow your system was still running the Intel binary (which would be a bug on our end). So to rule that out could you try the following:

1) Execute `uname -sm` from a Terminal

2) From where Quarto is installed remove the following directory entirely: `${quarto-dir}/bin/tools/deno-aarch64-apple-darwin`,  then, try re-running Quarto.

I'd expect the first to print `Darwin arm64` and the second to fail completely.

There may be a core dump for the crash available (although its not promising that there is no rust backtrace). If it exists you can find it using the "Console" Mac application  as described here https://support.apple.com/guide/console/reports-cnsl664be99a/mac

**Comment by jjallaire** [comment]
A longshot but you could also try running this pre-release build (which changes the binary that we use to launch deno): https://github.com/quarto-dev/quarto-cli/releases/tag/v1.2.66

**Comment by jph00** [comment]
>  1. Execute `uname -sm` from a Terminal
> 
$ uname -sm
Darwin arm64
>  1. From where Quarto is installed remove the following directory entirely: `${quarto-dir}/bin/tools/deno-aarch64-apple-darwin`, then, try re-running Quarto.
> 
$ sudo rm -rf /Applications/quarto/bin/tools/deno-aarch64-apple-darwin/
$ quarto render

That ran successfully. If I then re-run the installer, it fails again, until I delete the deno directory again, at which point it starts working again.

**Comment by jph00** [comment]
> A longshot but you could also try running this pre-release build (which changes the binary that we use to launch deno): https://github.com/quarto-dev/quarto-cli/releases/tag/v1.2.66
> 

That works :)

What change did you make to the binary?

**Comment by jjallaire** [comment]
We used to use a shell script for launching Deno. This was fine on Mac and Linux but on Windows created all kinds of problems (b/c there is no standard shell script w/ Command, PowerShell, Git Bash, etc.). 

So we re-wrote our launcher in Rust -- this solved all of our problems on Windows however it seems as if on the Mac an x86_64 launcher binary messes up correct functioning of aarch64 child processes! So the change you tested successfully is basically reverting to the shell script. If we want to bring the Rust binary back we just need to build it as a universal binary.

Thanks for reporting this and the follow-up on diagnosing. I am eternally grateful that we aren't now debugging a crash that "only happens on M2" :-)
