### ISSUE TITLE
Subscribe doesn't show up in the posts 

### ISSUE THREAD

**Issue by e-alizadeh** [quarto-dev/quarto-cli#2787]
### Bug description

Quarto version: 1.1.189
System: WSL (Windows 10) with Ubuntu terminal

The added subscription is not loaded in post pages as it does in the main blog page. 

I'm adding `margin-header: subscribe.html ` under `website` section in `_quarto.yml`.  

In the posts, only the filename "subscribe.html" appears instead of loading the file! You can see this in the screenshot below. You can check the HTML  code from the Developer inspect tool.
![blog_post](https://user-images.githubusercontent.com/30320825/194929036-76915865-f462-4ecd-a978-162000556d22.png)

FYI, the main blog page works fine as can be seen below. 
![blog_page](https://user-images.githubusercontent.com/30320825/194928994-cb8456de-9a71-44ee-9c22-ab3abc1b6a79.png)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
Thanks for reporting this- can you try using the latest prerelease build? This should be fixed there.

https://quarto.org/docs/download/prerelease.html

**Comment by e-alizadeh** [comment]
Thanks @dragonstyle. I can confirm that above works on the latest prelease build. 
However, if I add `margin-header: subscribe.html` to the `_metadata.yml` file in a post directory, OR adding it directly in the post frontmatter still show the text instead of loading it. Is that expected? 
The reason I'm interested in that is to have more control on the pages that load the subscription box.

**Comment by e-alizadeh** [comment]
Thanks @dragonstyle. It indeed worked.
