### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by fschaffner** [quarto-dev/quarto-cli#402]
I recently updated to version 0.9.80 (on macOS) and now I get "Invalid Date" in the compiled HTML document when I insert the current date in YAML with `r format(Sys.time(), '%e %B %Y')`. This worked for me in the older version and it also works in Rmarkdown. Is this a bug, or is there now a new way to use the current date (incl. formatting)?

```
---
title: "Test"
author: "Name"
date: "`r format(Sys.time(), '%e %B %Y')`"
format: html
---

Text

```

![Screenshot 2022-03-11 at 12 49 49](https://user-images.githubusercontent.com/30056330/157869787-1640a1f4-ff07-4566-a54c-101c5100aa15.png)

**Comment by dragonstyle** [comment]
I think this is likely a regression in our date handling. I'll take a look thank you for reporting it!

**Comment by dragonstyle** [comment]
Confirmed that this is a regression and should definitely work. I'll get a fix on the way...

**Comment by dragonstyle** [comment]
This should be resolved here:

https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.83

Thanks for catching this!

**Comment by fschaffner** [comment]
Thanks for the quick fix!

I downloaded and installed [quarto-0.9.83-macos.pkg](https://github.com/quarto-dev/quarto-cli/releases/download/v0.9.83/quarto-0.9.83-macos.pkg) and the date now shows up. However, the date is in the wrong format.

`format(Sys.time(), '%e %B %Y')` produces `"11 March 2022"` when run in the R console, but the date that shows up in the compiled HTML is `March 11, 2022`.

**Comment by dragonstyle** [comment]
Sure thing! That change is currently by design (we're actually parsing the date into a true date and formatting it rather than just treating it as an opaque string). You can specify `date-format` to control the formatting

```
date: "`r Sys.time()`"
date-format: medium
```

This has some benefits (for example, we can product formatted dates from different locales for the same input), but means that the date isn't passed through verbatim... One big downside that I've found right away is that there isn't a format available that matches your current format (and the custom formatting strings we provide are a little limited). This is something I'll have to look into improving.

Docs aren't great on `date-format` aren't great (I just discovered) - I'll update! Here is some info for now:

`date-format: <format>` 
The date format to use when displaying dates (e.g. d-M-yyyy).

You may either provide a date style (full, long, medium, or short) or a format string for formatting the date. The behavior of date styles varies depending upon locale, but examples in the en locale are as follows:

```
full
Saturday, February 5, 2022

long
February 5, 2022

medium
Feb 5, 2022

short
2/5/22
```

Learn more about supported format strings for date formatting values [here](https://deno.land/std@0.125.0/datetime).



Curious about your thoughts vs treating that date as verbatim...

**Comment by sbalci** [comment]
I have a similar issue with quarto books:

```
date: "`r Sys.time()`"
```

renders as

<img width="377" alt="Screen Shot 2022-03-12 at 23 15 09" src="https://user-images.githubusercontent.com/7208830/158033517-0e94dfac-838f-476f-ba43-9f680df4ffe8.png">

**Comment by dragonstyle** [comment]
@sbalci I'm taking a look at the book issue now.

@fschaffner I've updated the date format handling in Quarto to have a much richer set of supported formats which are outlined here: https://quarto.org/docs/reference/date-format.html

This should result in the output that you're looking for:

```yaml
date: "`r Sys.time()`"
date-format: "DD MMMM, YYYY"
```

**Comment by dragonstyle** [comment]
@sbalci This should be fixed in this commit: adb02c463a48f61751910c2666e8de358ea20a50 and a release should be out shortly at https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.96

This was a great bug, thank you for catching it!

**Comment by sbalci** [comment]
Hi @dragonstyle 
Thank you.
I am now getting result as "invalid date".

<img width="1561" alt="Screen Shot 2022-03-17 at 23 23 21" src="https://user-images.githubusercontent.com/7208830/158889078-6b8f81c9-ab74-4b8a-881f-033b3d847577.png">

**Comment by racing-focus** [comment]
has this been solved? I started using quarto after Mar 2022, but when I would like to use

```{r}
title: "title"
date: "`r Sys.time()`"
image: "preview.png"
```
It produces a date in the html I am producing, but the index page of my quarto blog says.

```{r}
Invalid Date.
``` 
Anyway. Cheers,

**Comment by mcanouil** [comment]
@racing-focus the issue was closed as resolved so likely to be resolved one way or another.
In this case, there are no reason to use inline knitr evaluation.
Use Quarto to use today's date or whatever, see <https://quarto.org/docs/reference/dates.html>.

**Comment by cderv** [comment]
@mcanouil still an issue that can be reproduce, and so a feature that does not work. 

@racing-focus I'll convert your report to an issue so that we make sure to fix for backward compatibility

**Comment by cderv** [comment]
@racing-focus Inline R code like this is now no more resolved by default without `engine: knitr` being active. 

So if you don't have any R chunk in your `.qmd` you need to add explicitly the engine
Try 
````yaml
title: "title"
date: "`r Sys.time()`"
image: "preview.png"
engine: knitr
````

This should now resolve the date correctly with R.

**Comment by racing-focus** [comment]
thank you very much. will one forever have to add:

```{r}
engine: knitr
```
to the .qmd file, or will the mechanics change at some point?

**Comment by mcanouil** [comment]
Only if you don't have any R code cell.

**Comment by paulcbauer** [comment]
So something like below is impossible now? Or how would I enter that?

date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"

Taken from the cookbook: https://bookdown.org/yihui/rmarkdown-cookbook/update-date.html

**Comment by cderv** [comment]
@paulcbauer the correct Quarto way would be to use 
```yaml
---
title: Test
format: html
date: last-modified
date-format: "[Last compiled on] D MMMM, YYYY"
---

Content

````

This is language agnostic and will work in all type of Quarto documents. 

See https://quarto.org/docs/reference/dates

What you described may still work for backward compatibility but requires the **knitr** to be active (explicitly or through a code chunk in a document - https://quarto.org/docs/computations/execution-options.html#engine-binding)

**Comment by paulcbauer** [comment]
Thanks! And is a linebreak possible? Something like..

"[First version: November 9, 2023;<br>This version: ]MMMM D, YYYY"

**Comment by cderv** [comment]
You should try, and I think it will works. 

Though if you check our reference (https://quarto.org/docs/reference/formats/html.html#title-author) and how default HTML template works, you can already set two dates 

````markdown
---
format: html
date: 
  value: 11/09/2023
  format: '[First version: ] MMMM DD, YYYY[;]'
date-modified: 
  value: today
  format: '[This version: ] MMMM DD, YYYY'
---

# content

````

Or even tweak the default description for the fields

````markdown
---
format: html
date: 11/09/2023
date-modified: today
date-format: 'MMMM DD, YYYY'
language: 
  title-block-published: First version
  title-block-modified: This version
---

# content

````

I let you play with what our docs described

**Comment by paulcbauer** [comment]
Hi @cderv, Thank you. In the end we needed it for pdf format and used the "hack" below (somehow the centering didn't work):

`date: today`
`date-format: "\\centering [First version: November 9, 2023\\newline\\centering This version: ]MMMM D, YYYY[\\newline\\centering Download most recent version: \\url{https://osf.io/6duw2/}]"`

**Comment by mcanouil** [comment]
It's because it is incorrect, "literals" have to be inside `[]` which is not the case of your first `\centering`.
Also you could add `{}` to delimit the scope of `\centering`.
Also, you can debug your $\LaTeX$ file using `keep-tex: true` in your YAML frontmatter to see what's going on in the code.

**Comment by paulcbauer** [comment]
@mcanouil  Many thanks for the tips!
