### ISSUE TITLE
html output self contained, css links in toc and anchors not working

### ISSUE THREAD

**Issue by jacekkotowski** [quarto-dev/quarto-cli#682]
```
---
title: "Extract data from many tables"
subtitle: "Test data"
author: "Jacek Kotowski"
date: "`r Sys.Date()`"
format: 
  html: 
    theme: simplex
    self-contained: true
    toc: true
    toc-location: right
    toc-title: Contents
    number-sections: true
    code-fold: show
    code-summary: "Show the code"
    code-tools: true
    default-image-extension: svg
    fig-format: svg
---

```
Such yaml will generate a file but anchors at the title are not visible and toc links do not get highlighted when clicked.

**Comment by jchiquet** [comment]
Hi,

Same problem seen here (on a more /too? complete example)

https://computo.sfds.asso.fr/template-computo-quarto/

The YAML metadata in the main document is as follows:

```
---
title: "Template for contribution to Computo"
subtitle: "Example based on the quarto system"
author:
  - name: "The Computo team"
    url: https://computorg.github.io/
    affiliation: Société Française de Statistique
    affiliation-url: https://www.sfds.asso.fr/
date: last-modified
abstract: >+
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur posuere vestibulum facilisis. Aenean pretium orci augue, quis lobortis libero accumsan eu. Nam mollis lorem sit amet pellentesque ullamcorper. Curabitur lobortis libero eget malesuada vestibulum. Nam nec nibh massa. Pellentesque porttitor cursus tellus. Mauris urna erat, rhoncus sed faucibus sit amet, venenatis eu ipsum.
citation:
  type: article-journal
  container-title: "Computo"
  doi: "xxxx"
  url: https://computo.sfds.asso.fr/template-computo-quarto
github: https://github.com/computorg/template-computo-quarto
bibliography: references.bib
repo: "template-computo-quarto"
---
```

which must be completed by the `_quarto.yml` file found there:

https://github.com/computorg/template-computo-quarto/blob/main/_quarto.yml

**Comment by dragonstyle** [comment]
> 
> https://github.com/computorg/template-computo-quarto/blob/main/_quarto.yml

I just cloned that repo and rendered the sample document locally. I wasn't able to reproduce the problem, but maybe I'm just not looking at things correctly. Can you clarify what you're seeing / or not seeing? When I scroll around, the TOC properly highlights and navigation appears to be working.

Here is what my rendered self contained version looks like:
[content.html.zip](https://github.com/quarto-dev/quarto-cli/files/8522801/content.html.zip)

Is this something different than what you're seeing?

Thanks for your help tracking this down...

**Comment by jchiquet** [comment]
Sorry, my mistake, read too fast, indeed it works with the last release.

Another issue, though: the author and affiliation-url are not working anymore (no link/anchor in the compiled HTML), but you may have removed temporarily this feature...

**Comment by dragonstyle** [comment]
Great news!

The urls not working is not intentional - let me take a look at that - I can reproduce that locally!

**Comment by dragonstyle** [comment]
Alright, fixed here:

153a3ace827bd36ecdd09a2a2e2279a7d97749ce

A fresh release is being built now!

**Comment by jlduan** [comment]
Hi @dragonstyle

Thanks for building this wonderful tool. I have problems regarding the TOC too. The links in the TOC are not properly highlighted. 

I have just rendered this repo https://computo.sfds.asso.fr/template-computo-quarto using the latest Quarto. The TOC doesn't work properly.


[content.html.zip](https://github.com/quarto-dev/quarto-cli/files/8526251/content.html.zip)

**Comment by dragonstyle** [comment]
It looks to me like this was generated using a version of Quarto a little older than the one which includes fixes. Can you make sure you're on the latest version of the main branch and try again?

<img width="1549" alt="Screen Shot 2022-04-20 at 8 53 06 PM" src="https://user-images.githubusercontent.com/261654/164350198-72b8dc91-031c-4026-87e4-ccde86b7926a.png">

<img width="1480" alt="Screen Shot 2022-04-20 at 8 52 37 PM" src="https://user-images.githubusercontent.com/261654/164350200-a1170f3c-ff41-44c9-905d-3ff4e8046652.png">

**Comment by jlduan** [comment]
@dragonstyle  Thanks for the reply. It is the latest version on the main, and I just rendered it again. It still doesn't work properly. 


<img width="618" alt="Screen Shot 2022-04-20 at 7 58 44 PM" src="https://user-images.githubusercontent.com/699489/164350905-de364eb6-4c36-4d88-9228-4a59be75fd0f.png">

> It looks to me like this was generated using a version of Quarto a little older than the one which includes fixes. Can you make sure you're on the latest version of the main branch and try again?
> 
> <img alt="Screen Shot 2022-04-20 at 8 53 06 PM" width="1549" src="https://user-images.githubusercontent.com/261654/164350198-72b8dc91-031c-4026-87e4-ccde86b7926a.png">
> 
> <img alt="Screen Shot 2022-04-20 at 8 52 37 PM" width="1480" src="https://user-images.githubusercontent.com/261654/164350200-a1170f3c-ff41-44c9-905d-3ff4e8046652.png">

**Comment by dragonstyle** [comment]
Hmm.... perhaps I diffed against the wrong version. When you mark the output as not self contained in the front matter, do they work? If not, do you see any errors in the javascript console (LMK if you need pointers on getting there - not familiar with how much web development tooling you've experienced!)?

**Comment by jlduan** [comment]
@dragonstyle 

It seems self-containing has noting to do with it. Changing to not self-contained doesn't fix it. I don't know much about web development. Is this error message helpful?

<img width="557" alt="Screen Shot 2022-04-20 at 8 13 22 PM" src="https://user-images.githubusercontent.com/699489/164352387-d631f560-a495-4eb7-9630-9e50cbd18754.png">

**Comment by dragonstyle** [comment]
You were 100% right and the issue should be fixed. A fresh release is building now. Thanks for following up!
