### ISSUE TITLE
column-page-inset seems not work properly if I set colgroup and columns width

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#8044]
### Bug description

Hi,
in [this page](https://aborruso.github.io/linee-guida-opendata/test_cit.html) I have inserted two html tables almost identical:

- in [the first one](https://github.com/aborruso/linee-guida-opendata/blob/main/test_cit.qmd#L14-L16) I have set the columns width. Here `:::{.column-page-inset}` does not work;
- in the [second one](https://github.com/aborruso/linee-guida-opendata/blob/main/test_cit.qmd#L180) I have no column width. Here `:::{.column-page-inset}` works;

The rendering of the [first](https://aborruso.github.io/linee-guida-opendata/test_cit.html#table-with-columns-width) and of the [second](https://aborruso.github.io/linee-guida-opendata/test_cit.html#table-without-columns-width).

### Steps to reproduce

Here the full code https://github.com/aborruso/linee-guida-opendata/blob/main/test_cit.qmd

````
---
csl: lg.csl
---

# Test {.unnumbered}

See at [@CAD]

## Table with columns width

:::{.column-page-inset}
<table border="0" cellspacing="0" class="table table-sm table-responsive">
  <colgroup span="3">
    <col style="width: 20%;">
    <col style="width: 60%;">
    <col style="width: 20%;">
  </colgroup>
  <tbody>
    <tr>
      <td><strong>Categoria tematica</strong></td>
      <td><strong>Disposizioni Regolamento</strong></td>
      <td><strong>Rif. indicazioni LG</strong></td>
    </tr>
    <tr>
      <td rowspan="3"><strong>Dati geospaziali</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; alle condizioni della licenza
        Creative Commons BY 4.0 o di una licenza aperta equivalente o meno restrittiva; <br />&bull; in un formato
        aperto leggibile meccanicamente, pubblicamente <br />documentato e riconosciuto dall&rsquo;Unione o a livello
        internazionale; <br />&bull; tramite interfacce di programmazione delle applicazioni ("API") e download in
        blocco; <br />&bull; [nella versione pi&ugrave; aggiornata].</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO 27</td>
    </tr>
    <tr>
      <td>I metadati che descrivono le serie di dati rientranti nell&rsquo;ambito di applicazione delle categorie
        tematiche di dati INSPIRE contengono almeno gli elementi di metadati di cui al regolamento (CE) n. 1205/2008
        della Commissione.</td>
      <td>REQUISITO 16</td>
    </tr>
    <tr>
      <td>Per l'attuazione delle serie di dati sulle parcelle di riferimento e sulle parcelle agricole, gli Stati membri
        tengono conto dell'attuazione in corso della direttiva 2007/2/CE nonch&eacute; degli obblighi di cui
        all'articolo 67, paragrafi 3 e 5, del regolamento (UE) 2021/2116.</td>
      <td>REQUISITO 14</td>
    </tr>
    <tr>
      <td rowspan="4"><strong>Dati relativi all&rsquo;osservazione della terra e all&rsquo;ambiente</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; alle condizioni della licenza
        Creative Commons BY 4.0 o di una licenza aperta equivalente o meno restrittiva; <br />&bull; in un formato
        aperto leggibile meccanicamente, pubblicamente documentato e riconosciuto dall&rsquo;Unione o a livello
        internazionale; <br />&bull; tramite API e download in blocco (per le versioni storiche delle serie di dati: API
        o download in blocco, per quanto possibile e opportuno).</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO 27</td>
    </tr>
    <tr>
      <td>I metadati che descrivono i dati rientranti nell&rsquo;ambito di applicazione delle categorie tematiche di
        dati INSPIRE contengono almeno gli elementi di metadati di cui all'allegato del regolamento (CE) n. 1205/2008.
      </td>
      <td>REQUISITO 16</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td>Le serie di dati utilizzano vocabolari e tassonomie controllati, pubblicamente documentati e riconosciuti
        dall&rsquo;Unione o a livello internazionale, se disponibili.</td>
      <td>Par. 5.1.4</td>
    </tr>
    <tr>
      <td rowspan="3"><strong>Dati meteorologici</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; alle condizioni della licenza
        Creative Commons BY 4.0 o di una licenza aperta equivalente o meno restrittiva; <br />&bull; in uno qualsiasi
        dei formati specificati nella tabella presente al par. 3.2 dell&rsquo;Allegato I o in un altro formato aperto,
        leggibile meccanicamente, riconosciuto dall&rsquo;Unione o a livello internazionale; <br />&bull; tramite API e
        download in blocco, ad eccezione della serie di dati &laquo;dati dei modelli NWP&raquo;, che &egrave; resa
        disponibile solo tramite API; <br />&bull; [in base alla frequenza e alla tempestivit&agrave; di aggiornamento
        specificate nella tabella presente nel par. 3.2 dell&rsquo;Allegato I].</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO
        27<br />Allegato B &ndash; 2.4</td>
    </tr>
    <tr>
      <td>I metadati che descrivono la serie di dati sono completi e disponibili sul Web in un formato aperto e
        ampiamente utilizzato, leggibile meccanicamente.</td>
      <td>REQUISITO 15</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td rowspan="4"><strong>Dati statistici</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; [con la frequenza richiesta dalla
        legislazione corrispondente di cui al punto 4.1. dell&rsquo;Allegato I (ad es. mensile, trimestrale, annuale)];
        <br />&bull; alle condizioni della licenza Creative Commons BY 4.0 o di una licenza aperta equivalente o meno
        restrittiva; <br />&bull; in un formato CSV, XML (SDMX), JSON o in altro formato aperto leggibile
        meccanicamente, pubblicamente documentato e riconosciuto dall&rsquo;Unione o a livello
        internazionale;<br />&bull; tramite API e download in blocco;</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO
        27<br />Allegato B &ndash; 2.2/2.4</td>
    </tr>
    <tr>
      <td>I metadati che descrivono le serie di dati sono disponibili sotto forma di file strutturato ben sviluppato
        contenente almeno una descrizione di dati statistici, concetti statistici, metodologie e informazioni sulla
        qualit&agrave; dei dati.</td>
      <td>REQUISITO 15</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td>Le serie di dati utilizzano vocabolari e tassonomie controllati, pubblicamente documentati e riconosciuti
        dall&rsquo;Unione o a livello internazionale, se disponibili.</td>
      <td>Par. 5.1.4</td>
    </tr>
    <tr>
      <td rowspan="3"><strong>Dati relativi alle imprese e alla propriet&agrave; delle imprese</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; [senza indebito ritardo dopo
        l'ultimo aggiornamento]; <br />&bull; alle condizioni della licenza Creative Commons BY 4.0 o di una licenza
        aperta equivalente o meno restrittiva, con condizioni supplementari relative al riutilizzo dei dati personali,
        se del caso; <br />&bull; in un formato aperto leggibile meccanicamente e riconosciuto <br />dall&rsquo;Unione o
        a livello internazionale (XHTML per i documenti che <br />rientrano nell&rsquo;ambito di applicazione del
        Regolamento Delegato (UE) 2018/815 della Commissione; altri formati, se e ove prescritto dal diritto dell'Unione
        applicabile), con metadati completi ([per i documenti che rientrano nell&rsquo;ambito di applicazione del
        Regolamento Delegato (UE) 2016/1437 della Commissione, i metadati specificati in tale regolamento, se del caso;]
        per gli altri documenti, i metadati prescritti dal diritto dell&rsquo;UE applicabile, se del caso); la
        leggibilit&agrave; meccanica non &egrave; imposta per i dati conservati in formati non leggibili meccanicamente
        (ad es. documenti e conti aziendali scannerizzati) o per I campi di dati non strutturati/non leggibili
        meccanicamente inclusi come parte di documenti leggibili meccanicamente; <br />&bull; tramite API e download in
        blocco; <br />&bull; [a livello di singola azienda].</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 15<br />REQUISITO
        7<br />REQUISITO 27<br />Allegato B &ndash; 2.4</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td>Le serie di dati utilizzano vocabolari e tassonomie controllati, pubblicamente documentati e riconosciuti
        dall&rsquo;Unione o a livello internazionale, se disponibili, come il Core Business Vocabulary.</td>
      <td>Par. 5.1.4</td>
    </tr>
    <tr>
      <td rowspan="4"><strong>Dati relativi alla mobilit&agrave;</strong></td>
      <td>Le serie di dati della rete di trasporto sono messe a disposizione per il riutilizzo<br />&bull;
        [immediatamente dopo l&rsquo;ultimo aggiornamento]; <br />&bull; alle condizioni della licenza Creative Commons
        BY 4.0 o di una licenza aperta equivalente o meno restrittiva; <br />&bull; in un formato aperto leggibile
        meccanicamente e riconosciuto dall&rsquo;Unione o a livello internazionale;<br />&bull; tramite API e download
        in blocco;<br />&bull; [nella versione pi&ugrave; aggiornata].</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO 27</td>
    </tr>
    <tr>
      <td>I metadati che descrivono le serie di dati sulle reti di trasporto contengono almeno gli elementi di metadati
        definiti nel Regolamento (CE) n. 1205/2008.</td>
      <td>REQUISITO 16</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td>Le serie di dati utilizzano vocabolari e tassonomie controllati, pubblicamente documentati e riconosciuti
        dall&rsquo;Unione o a livello internazionale, se disponibili.</td>
      <td>Par. 5.1.4</td>
    </tr>
  </tbody>
</table>
:::


## Table without columns width

:::{.column-page-inset}
<table border="0" cellspacing="0" class="table table-sm table-responsive">
  <colgroup span="3"></colgroup>
  <tbody>
    <tr>
      <td><strong>Categoria tematica</strong></td>
      <td><strong>Disposizioni Regolamento</strong></td>
      <td><strong>Rif. indicazioni LG</strong></td>
    </tr>
    <tr>
      <td rowspan="3"><strong>Dati geospaziali</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; alle condizioni della licenza
        Creative Commons BY 4.0 o di una licenza aperta equivalente o meno restrittiva; <br />&bull; in un formato
        aperto leggibile meccanicamente, pubblicamente <br />documentato e riconosciuto dall&rsquo;Unione o a livello
        internazionale; <br />&bull; tramite interfacce di programmazione delle applicazioni ("API") e download in
        blocco; <br />&bull; [nella versione pi&ugrave; aggiornata].</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO 27</td>
    </tr>
    <tr>
      <td>I metadati che descrivono le serie di dati rientranti nell&rsquo;ambito di applicazione delle categorie
        tematiche di dati INSPIRE contengono almeno gli elementi di metadati di cui al regolamento (CE) n. 1205/2008
        della Commissione.</td>
      <td>REQUISITO 16</td>
    </tr>
    <tr>
      <td>Per l'attuazione delle serie di dati sulle parcelle di riferimento e sulle parcelle agricole, gli Stati membri
        tengono conto dell'attuazione in corso della direttiva 2007/2/CE nonch&eacute; degli obblighi di cui
        all'articolo 67, paragrafi 3 e 5, del regolamento (UE) 2021/2116.</td>
      <td>REQUISITO 14</td>
    </tr>
    <tr>
      <td rowspan="4"><strong>Dati relativi all&rsquo;osservazione della terra e all&rsquo;ambiente</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; alle condizioni della licenza
        Creative Commons BY 4.0 o di una licenza aperta equivalente o meno restrittiva; <br />&bull; in un formato
        aperto leggibile meccanicamente, pubblicamente documentato e riconosciuto dall&rsquo;Unione o a livello
        internazionale; <br />&bull; tramite API e download in blocco (per le versioni storiche delle serie di dati: API
        o download in blocco, per quanto possibile e opportuno).</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO 27</td>
    </tr>
    <tr>
      <td>I metadati che descrivono i dati rientranti nell&rsquo;ambito di applicazione delle categorie tematiche di
        dati INSPIRE contengono almeno gli elementi di metadati di cui all'allegato del regolamento (CE) n. 1205/2008.
      </td>
      <td>REQUISITO 16</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td>Le serie di dati utilizzano vocabolari e tassonomie controllati, pubblicamente documentati e riconosciuti
        dall&rsquo;Unione o a livello internazionale, se disponibili.</td>
      <td>Par. 5.1.4</td>
    </tr>
    <tr>
      <td rowspan="3"><strong>Dati meteorologici</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; alle condizioni della licenza
        Creative Commons BY 4.0 o di una licenza aperta equivalente o meno restrittiva; <br />&bull; in uno qualsiasi
        dei formati specificati nella tabella presente al par. 3.2 dell&rsquo;Allegato I o in un altro formato aperto,
        leggibile meccanicamente, riconosciuto dall&rsquo;Unione o a livello internazionale; <br />&bull; tramite API e
        download in blocco, ad eccezione della serie di dati &laquo;dati dei modelli NWP&raquo;, che &egrave; resa
        disponibile solo tramite API; <br />&bull; [in base alla frequenza e alla tempestivit&agrave; di aggiornamento
        specificate nella tabella presente nel par. 3.2 dell&rsquo;Allegato I].</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO
        27<br />Allegato B &ndash; 2.4</td>
    </tr>
    <tr>
      <td>I metadati che descrivono la serie di dati sono completi e disponibili sul Web in un formato aperto e
        ampiamente utilizzato, leggibile meccanicamente.</td>
      <td>REQUISITO 15</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td rowspan="4"><strong>Dati statistici</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; [con la frequenza richiesta dalla
        legislazione corrispondente di cui al punto 4.1. dell&rsquo;Allegato I (ad es. mensile, trimestrale, annuale)];
        <br />&bull; alle condizioni della licenza Creative Commons BY 4.0 o di una licenza aperta equivalente o meno
        restrittiva; <br />&bull; in un formato CSV, XML (SDMX), JSON o in altro formato aperto leggibile
        meccanicamente, pubblicamente documentato e riconosciuto dall&rsquo;Unione o a livello
        internazionale;<br />&bull; tramite API e download in blocco;</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO
        27<br />Allegato B &ndash; 2.2/2.4</td>
    </tr>
    <tr>
      <td>I metadati che descrivono le serie di dati sono disponibili sotto forma di file strutturato ben sviluppato
        contenente almeno una descrizione di dati statistici, concetti statistici, metodologie e informazioni sulla
        qualit&agrave; dei dati.</td>
      <td>REQUISITO 15</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td>Le serie di dati utilizzano vocabolari e tassonomie controllati, pubblicamente documentati e riconosciuti
        dall&rsquo;Unione o a livello internazionale, se disponibili.</td>
      <td>Par. 5.1.4</td>
    </tr>
    <tr>
      <td rowspan="3"><strong>Dati relativi alle imprese e alla propriet&agrave; delle imprese</strong></td>
      <td>Le serie di dati sono messe a disposizione per il riutilizzo: <br />&bull; [senza indebito ritardo dopo
        l'ultimo aggiornamento]; <br />&bull; alle condizioni della licenza Creative Commons BY 4.0 o di una licenza
        aperta equivalente o meno restrittiva, con condizioni supplementari relative al riutilizzo dei dati personali,
        se del caso; <br />&bull; in un formato aperto leggibile meccanicamente e riconosciuto <br />dall&rsquo;Unione o
        a livello internazionale (XHTML per i documenti che <br />rientrano nell&rsquo;ambito di applicazione del
        Regolamento Delegato (UE) 2018/815 della Commissione; altri formati, se e ove prescritto dal diritto dell'Unione
        applicabile), con metadati completi ([per i documenti che rientrano nell&rsquo;ambito di applicazione del
        Regolamento Delegato (UE) 2016/1437 della Commissione, i metadati specificati in tale regolamento, se del caso;]
        per gli altri documenti, i metadati prescritti dal diritto dell&rsquo;UE applicabile, se del caso); la
        leggibilit&agrave; meccanica non &egrave; imposta per i dati conservati in formati non leggibili meccanicamente
        (ad es. documenti e conti aziendali scannerizzati) o per I campi di dati non strutturati/non leggibili
        meccanicamente inclusi come parte di documenti leggibili meccanicamente; <br />&bull; tramite API e download in
        blocco; <br />&bull; [a livello di singola azienda].</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 15<br />REQUISITO
        7<br />REQUISITO 27<br />Allegato B &ndash; 2.4</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td>Le serie di dati utilizzano vocabolari e tassonomie controllati, pubblicamente documentati e riconosciuti
        dall&rsquo;Unione o a livello internazionale, se disponibili, come il Core Business Vocabulary.</td>
      <td>Par. 5.1.4</td>
    </tr>
    <tr>
      <td rowspan="4"><strong>Dati relativi alla mobilit&agrave;</strong></td>
      <td>Le serie di dati della rete di trasporto sono messe a disposizione per il riutilizzo<br />&bull;
        [immediatamente dopo l&rsquo;ultimo aggiornamento]; <br />&bull; alle condizioni della licenza Creative Commons
        BY 4.0 o di una licenza aperta equivalente o meno restrittiva; <br />&bull; in un formato aperto leggibile
        meccanicamente e riconosciuto dall&rsquo;Unione o a livello internazionale;<br />&bull; tramite API e download
        in blocco;<br />&bull; [nella versione pi&ugrave; aggiornata].</td>
      <td>REQUISITO 20<br />REQUISITO 21<br />REQUISITO 2<br />REQUISITO 3<br />REQUISITO 7<br />REQUISITO 27</td>
    </tr>
    <tr>
      <td>I metadati che descrivono le serie di dati sulle reti di trasporto contengono almeno gli elementi di metadati
        definiti nel Regolamento (CE) n. 1205/2008.</td>
      <td>REQUISITO 16</td>
    </tr>
    <tr>
      <td>Le serie di dati sono descritte in una documentazione online completa e accessibile al pubblico che descrive
        almeno la struttura e la semantica dei dati.</td>
      <td>Par. 5.1.5</td>
    </tr>
    <tr>
      <td>Le serie di dati utilizzano vocabolari e tassonomie controllati, pubblicamente documentati e riconosciuti
        dall&rsquo;Unione o a livello internazionale, se disponibili.</td>
      <td>Par. 5.1.4</td>
    </tr>
  </tbody>
</table>
:::

````

### Expected behavior

I expect `{.column-page-inset}` to work either way

### Actual behavior

`{.column-page-inset}` does not work if I set columns width

### Your environment

I use VSCode, and my system is Debian 11

### Quarto check output

```
Quarto 1.4.533
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.533
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2020

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /usr/bin/python3
      Jupyter: 5.3.2
      Kernels: bash, python3

(|) Checking Jupyter engine render....Could create runtime directory for jupyter transport.
This is possibly a permission issue in the environment Quarto is running in.
Please consult the following documentation for more information:
https://github.com/quarto-dev/quarto-cli/issues/4594#issuecomment-1619177667
[✓] Checking Jupyter engine render....OK

R scripting front-end version 4.0.4 (2021-02-15)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cderv** [comment]
It seems you are adding HTML raw tables. 

Can  you add them into raw block ? 

````markdown
```{=html}
<table border="0" cellspacing="0" class="table table-sm table-responsive">
(...)
</table>
```
````

This is described at https://quarto.org/docs/authoring/tables.html#html-tables 

I believe this will help the correct parsing and it should work fine 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/34edffaf-5504-4b4d-93e9-d88241441282)

**Comment by aborruso** [comment]
Thank you @cderv. I have applied it, and now I can set properly columns width: https://aborruso.github.io/linee-guida-opendata/test_cit.html

But I have two related problems:

- the `.column-page-inset` class works, but the left sidebar is not off and covers the table (see the image below);
- I would like to use footnotes and [I have added one](https://github.com/aborruso/linee-guida-opendata/blob/main/test_cit.qmd#L204) using `<span data-qmd="lorem [^footsample]"></span>`, but in the rendering I have `REQUISITO 20lorem [^footsample]`. But here I probably didn't understand something, or I'm doing something wrong.


![image](https://github.com/quarto-dev/quarto-cli/assets/30607/2da13cac-4609-457f-9c6c-b3d08d2ac533)

**Comment by mcanouil** [comment]
I don't think you can override the sidebar in book.
Having the left sidebar is kind of the whole point of the book format.

Regarding the footnote, can you make a small and simple example? Yours is 350 lines.

**Comment by aborruso** [comment]
> Regarding the footnote, can you make a small and simple example? Yours is 350 lines.

Thank you @mcanouil.

Here the example:

- the rendered page https://aborruso.github.io/linee-guida-opendata/small_table.html
- the code https://github.com/aborruso/linee-guida-opendata/blob/main/small_table.qmd

**Comment by aborruso** [comment]
> I don't think you can override the sidebar in book.
> Having the left sidebar is kind of the whole point of the book format.

Thank you @mcanouil it seems that I can override sidebar in book:

https://aborruso.github.io/linee-guida-opendata/debug/column-page-inset.html#second-table-with-column-page-inset

But it seems that it's a problem if the `.column-page-inset` is at the beginning. It looks like a bug to me. What do you think?

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/9e6a55e0-68eb-4139-9cb2-8df6e3a6d362)

**Comment by mcanouil** [comment]
It might require some tweaks to allow some space before the inset.

@dragonstyle will have a better view on this.

PS: When I said override, I meant you can't remove the sidebar if you set it in the first place.

**Comment by aborruso** [comment]
> PS: When I said override, I meant you can't remove the sidebar if you set it in the first place.

I understood you to mean that in a book it was somehow untouchable. Sorry, I had misunderstood.

**Comment by mcanouil** [comment]
> I understood you to mean that in a book it was somehow untouchable. Sorry, I had misunderstood

No worries, I wasn't clear.
Side note: Personally I would avoid touching it even (if it is collapsible) as it is used for navigation.
Instead I would tweak the table and expand only on the right margin.

**Comment by aborruso** [comment]
> Instead I would tweak the table and expand only on the right margin.

You are right it is a solution. I leave it to you to check if it is a bug or a design choice.

As soon as you can tell me what you think about the fact that I can't get footnotes to work?

**Comment by aborruso** [comment]
@mcanouil  please when you have some time, can you tell me what I'm doing wrong [here](https://github.com/quarto-dev/quarto-cli/issues/8044#issuecomment-1871096523)?

**Comment by dragonstyle** [comment]
I believe that we fixed the issue with the sidebar overlap (I made a couple changes related to this element's height recently) - in my local testing the current version doesn't exhibit the issue:

![Screenshot 2024-01-03 at 12 40 51 PM](https://github.com/quarto-dev/quarto-cli/assets/261654/c7f783c9-d96a-435c-8fad-528376d54d4e)


I'm going to close the issue, please feel free to re-open if the issue persists!

**Comment by aborruso** [comment]
> I'm going to close the issue, please feel free to re-open if the issue persists!

As a user, unfortunately, I do not have permission to re-open the issue.

In my [rendered page](https://ondata.github.io/linee-guida-opendata/test_cit.html) (the [code](https://github.com/ondata/linee-guida-opendata/blob/main/test_cit.qmd)), I still have the left menu covering the table.

Thank you very much @dragonstyle 

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/749eac87-210a-4a0c-b1d8-63225a251549)

**Comment by dragonstyle** [comment]
Can you please try again with a more recent pre-release version? I made the fix this week so it likely just that you are using an older version.

**Comment by aborruso** [comment]
> Can you please try again with a more recent pre-release version? I made the fix this week so it likely just that you are using an older version.

I'm stupid: I forgot to do the update. It works!

Thank you again

**Comment by dragonstyle** [comment]
Thanks for taking the time to report the issue, that was a very annoying regression and I'm glad we had a number of people (yourself included) catching it!
