### ISSUE TITLE
[conflict with Hugo]: quarto rendering interferes with Hugo shortcodes

### ISSUE THREAD

**Issue by prosoitos** [quarto-dev/quarto-cli#888]
Thanks for the ultra cool project! 🙂 

Unless I am mistaken (very possible!), it looks like the rendering of quarto from .qmd to .md adds escape characters which prevent the usage of Hugo shortcodes.

Here is an example:

I have a shortcode in Hugo called a.html that I use with:

```
{{<a "some content">}}
```

When Hugo renders my markdown file, the shortcode gets expanded into some html code.

Now, the problem is that if I use `{{<a "some content">}}` in my .qmd file, it gets rendered by quarto in the .md file as:

```
{{<\a "some content"\>}}
```

So Hugo cannot process the shortcode anymore and it appears in the html file as is.

Am I missing something? If not, is there a workaround? Or could this be addressed somehow?

Thank you!!!

**Comment by prosoitos** [comment]
Note that shortcodes are one of the cool features of Hugo and while one workaround would of course be not to use them anymore and to use raw html instead, that would be a bit of a bummer.

**Comment by jjallaire** [comment]
Yes, we are big believers in shortcodes (and hugo shortcodes in particular). We actually have our own shortcode implementation (with syntax taken 100% from hugo): https://quarto.org/docs/authoring/shortcodes.html

I think we can make your scenario work as well. We just need to make sure that when targeting markdown/hugo we allow the "unrecognized" shortcode to pass through without pandoc escaping it. Will post back here once we've sorted that out.

**Comment by jjallaire** [comment]
Okay, this should be resolved here: https://github.com/quarto-dev/quarto-cli/commit/a1c004b747ae43e10b607762e003ba5962e139e1 (and available in our latest release)

**Comment by prosoitos** [comment]
Great! 🙂 Thank you for looking into this so quickly!!!!

**Comment by prosoitos** [comment]
Actually, while a1c004b perfectly solved the problem that I described in this issue, I later realized that the problem is a little bit more complex and the fix doesn't work in all situations:

In addition to the escape characters at the start and end of all shortcodes (that a1c004b addresses), a number of special characters within the shortcodes (so far, I have noticed it for `_`, `[`, `]`, and `#`, but there could be more) also get escaped.

Consequently, whenever the body of a shortcode contains these, the shortcode is rendered by Hugo, but into something wrong (due to the additional `\` character(s)).

a1c004b let's all shortcodes be rendered by quarto and then attempts to address the problem by removing unwanted escape characters. It feels a little bit hacky and a cleaner fix would be to prevent quarto from processing unrecognized shortcodes in the first place. In addition, this hacky reversal doesn't address the additional problem that I was initially unaware of (and thus didn't mention at all when I opened this issue).

I realize that excluding unrecognized shortcodes from rendering by quarto might involve a lot more work and be hard to implement (I haven't looked at the quarto source code and have no idea at this point what it would involve).

In that case, I guess, I can live with the problem: only so many shortcodes contain special characters in their body and I can use raw html in those cases.

a1c004b provided a tremendous improvement since I used not to be able to use any Hugo shortcode to now only having problems with a few here and there.

So I am not re-opening the issue and leave it up to you whether you think that this is worth addressing or not.

Thank you!!

**Comment by jjallaire** [comment]
Hi there, thanks for pointing this out!

This additional fix (https://github.com/quarto-dev/quarto-cli/commit/bdc92dd4aff5c088a81426510b2bc6005eb70b6d) should prevent the excess escaping that you are observing. That was incidentally the initial fix I tried but I found that it didn't prevent escaping of shortcodes of the following form (from your initial motivating example):

```
{{<a "some content">}}
```

So we still do need the hacky last ditch substitution for this case (I think it's the `a` right up against the `<` that is causing pandoc to try to escape it so its not seen as an HTML tag). 

This is is in v0.9.514 (just released): https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.514

**Comment by prosoitos** [comment]
Thank you for your quick reply again!

I am now using v0.9.515 and I am still experiencing the same problem.

Here are examples:

```md
{{<a "https://stackoverflow.com/tags/julia" "[julia] tag on Stack Overflow">}} \
{{<a "https://twitter.com/search?q=%23julialang" "#julialang hashtag on Twitter">}} \
{{<a "https://en.wikipedia.org/wiki/Lisp_(programming_language)" "Lisp">}}
```

**Comment by prosoitos** [comment]
They get rendered in the .md file as the following:

```md
{{<a "https://stackoverflow.com/tags/julia" "\[julia\] tag on Stack Overflow">}}  
{{<a "https://twitter.com/search?q=%23julialang" "\#julialang hashtag on Twitter">}}
{{<a "https://en.wikipedia.org/wiki/Lisp\_(programming_language)" "Lisp">}}
```

**Comment by jjallaire** [comment]
We aren't catching those because they don't conform to the Quarto shortcode syntax (so they bypass the code I put in to protect from escaping). You might need to manually protect shortcodes from escaping by using a "raw" markdown block (or inline). For example:

````markdown
```{=markdown}
{{<a "https://stackoverflow.com/tags/julia" "[julia] tag on Stack Overflow">}}
{{<a "https://twitter.com/search?q=%23julialang" "#julialang hashtag on Twitter">}}
{{<a "https://en.wikipedia.org/wiki/Lisp_(programming_language)" "Lisp">}}
```

`{{<a "https://stackoverflow.com/tags/julia" "[julia] tag on Stack Overflow">}}`{=markdown}
````

**Comment by prosoitos** [comment]
Thank you very much J. J. for all your time helping with this!

I just tried this, but I am running into another problem:

Indeed, now my shortcode expressions aren't quoted anymore, but quarto renders raw markdown blocks by replacing the double quotes by the more stylistic [U+201C](https://www.compart.com/en/unicode/U+201C) characters.

And unfortunately, Hugo does not recognize those. I thus get the error message:

```
[...] unrecognized character in shortcode action: U+201C '“'. Note: Parameters with non-alphanumeric args must be quoted
```

Honestly, if you think that this might affect other people and that it might improve quarto to address it, you can keep thinking about it, but otherwise, I am happy to use raw html in my quote whenever the arguments I pass to one of my shortcodes countain special characters.

**Comment by prosoitos** [comment]
I should probably also learn about quarto shortcodes. Maybe I can re-write my Hugo shortcodes to make them compatible.

**Comment by jjallaire** [comment]
Yes, I think raw html is the best course here. It's hard for us to elide arbitrary text sequences from processing by pandoc -- to really solve this we'd need to fully port the Hugo shortcode parsing primitives to Javascript and do this in a separate pass over the input document. Given that most shortcodes already pass through w/o trouble I think having the page author expressly tell us when to leave content alone is the best way.

I'd also agree that using Quarto shortcodes is all else being equal better than Hugo shortcodes as they are at least portable to other output formats / site generation systems.

**Comment by prosoitos** [comment]
Sounds good.

Thank you so much J. J.

I'll move to quarto shortcodes.

**Comment by jjallaire** [comment]
This is a result of a couple of things:

(1) In order to "protect" the Hugo shortcode from Pandoc escaping behavior we enclose it is in raw markdown inline;

(2) Pandoc seems to have a rule that raw inlines can't be link targets (so the link syntax gets escaped).

The solution is that you need to protect the entire construct from Pandoc markdown rendering by using a raw markdown block (or inline) as appropriate. This wasn't previously well documented but the docs have been updated here:

https://quarto.org/docs/output-formats/hugo.html#shortcodes

Note that we also needed to fix a bug related to short codes to make this work properly. This fix is available in the v0.9.655 release: https://github.com/quarto-dev/quarto-cli/releases/latest

**Comment by mivalek** [comment]
Thanks a lot JJ, that's great!

Does this mean that the extra `{}` syntax is discouraged? (I rather like it)
Speaking of which, I noticed that a comma right after the closing third `}` confuses the parser:
`{{{< shortcode >}}},` renders in .md as `{{{< shortcode >}}},` instead of `{{< shortcode >}},`. I haven't tested other punctuation chars, just thought you might like to know.

Thanks again 🙂

**Comment by jjallaire** [comment]
I too like the extra `{}` syntax but sadly while investigating this issue I discovered that its implementation is incomplete (esp. w/ adjacent characters). I will hopefully relatively soon fix this and then that can be used in preference to the the raw markdown block.

**Comment by jjallaire** [comment]
We are now handling the extra `{}` correctly (as well as have better handling of quotes) so more scenarios should work without going into full escape mode.
